/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package online.gladikov.hibernate;

import org.junit.jupiter.api.Test;

class DNSAppTest {
    @Test void appHasAGreeting() {
    }
}
